config/routes.rb
Rails.application.routes.draw do

  namespace 'toolset' do
    resources :maps
  end

end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/toolset/maps_controller.rb
class Toolset::MapsController < ToolsetController

  def index
    @maps = Map.all
  end

end

app/controllers/toolset_controller.rb
class ToolsetController < ApplicationController
  layout 'toolset'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav_toolset.html.slim
.navbar.navbar-default
  .container
    .navbar-collapse.collapse
      ul.nav.navbar-nav
        li= link_to toolset_maps_path do
          | Карты

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Engine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/toolset.html.slim
doctype html
html lang="ru" ng-app="smp"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    title
      | Engine Toolset
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  body
    == render partial: 'layouts/nav_toolset'
    .container
      = yield

    footer

app/views/toolset/maps/index.html.slim
ul.nav.nav-pills
  = link_to 'Добавить карту', new_toolset_map_path, class: 'btn btn-primary'

.panel.panel-default
  .panel-heading
    | Список карт

  table.table
    tr
      th Название
      th Размер
    - @maps.each do |map|
      tr
        td
          =' map.name
        td
          =' map.width
          | x
          =' map.height